#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
# export SXHKD_SHELL='/usr/bin/sh'
# export QT_QPA_PLATFORMTHEME=qt5ct
# pgrep -x fcitx5 >/dev/null || fcitx5 &
# /home/aurora/xrander.sh &
# pgrep -x polybar >/dev/null || ~/.scripts/launch.sh >/dev/null &
# pgrep -x picom >/dev/null || picom --experimental-backends >>/var/log/picom.log 2>&1 &
# pgrep -x feh >/dev/null || /home/aurora/.scripts/random_wallpaper.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# border color
bspc config focused_border_color "#81A1C1"
bspc config active_border_color "#88C0D0"
# bspc config norma_border_color "#81A1C1"
bspc config presel_feedback_color "#81A1C1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Google-chrome desktop='^2' focus=on
bspc rule -a dida desktop='^5' focus=on
bspc rule -a Thunar state=floating
bspc rule -a "wechat.exe" state=floating
# bspc rule -a flameshot manage=off
# bspc rule -a feh manage=off
bspc rule -a ppic manage=off
bspc rule -a st-floating state=floating
bspc rule -a wezterm-floating state=floating
